name: Update Timestamp and User Info
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-info:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create or update info file
        run: |
          # Create the content with current UTC time and user info
          cat > STATUS.md << EOL
          Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): $(date -u '+%Y-%m-%d %H:%M:%S')
          Current User's Login: luckyaiman
          EOL

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add STATUS.md
          
          # Only commit and push if there are changes
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update timestamp and user info: $(date -u '+%Y-%m-%d %H:%M:%S')"
            git push
          )
